### PR TITLE
Adding support for activeBids

### PR DESCRIPTION
**Pull request by Will-Hyde**
Adding support for ActiveBids in datastore API. Additionally, CancelledBids and BidPlaced items should appear in the domain history.

I decided against adding additional sort options, because as activeBids are an array of items its not possible to sort activebids as discussed in the ticket

### CODE REVIEW

**Comment by Will-Hyde** [comment]
One open question:

Is it acceptable to expose the bid SignedMessage? Is that something that would be useful on the front end for the consumers?
@RyanCross  @JamesEarle

**Comment by RyanCross** [comment]
> Adding support for ActiveBids in datastore API. Additionally, CancelledBids and BidPlaced items should appear in the domain history.
> 
> I decided against adding additional sort options, because as activeBids are an array of items its not possible to sort activebids as discussed in the ticket

Can you expand on this? We have requirements to be able to sort active bids by recency and price.

**Comment by Will-Hyde** [comment]
> > Adding support for ActiveBids in datastore API. Additionally, CancelledBids and BidPlaced items should appear in the domain history.
> > I decided against adding additional sort options, because as activeBids are an array of items its not possible to sort activebids as discussed in the ticket
> 
> Can you expand on this? We have requirements to be able to sort active bids by recency and price. I would expect that adding support would be two-fold. Adding support for two different types of activeBids sorting at the api level, and changes in the data-store to support that sorting (either by utilizing the advanced sorting rules pattern, or modifying the query)

ActiveBids are an array, which makes it so mongo isnt able to sort them in a similar way to other properties. If we want to sort bids by recency and price, I would recommend we add an entirely new endpoint to retrieve bids from a domain and enable bid sorting on that. Otherwise, it just wouldnt make a lot of sense.

**Comment by RyanCross** [comment]
> > > Adding support for ActiveBids in datastore API. Additionally, CancelledBids and BidPlaced items should appear in the domain history.
> > > I decided against adding additional sort options, because as activeBids are an array of items its not possible to sort activebids as discussed in the ticket
> > 
> > 
> > Can you expand on this? We have requirements to be able to sort active bids by recency and price. I would expect that adding support would be two-fold. Adding support for two different types of activeBids sorting at the api level, and changes in the data-store to support that sorting (either by utilizing the advanced sorting rules pattern, or modifying the query)
> 
> ActiveBids are a nested array, which makes it so mongo isnt able to sort them in a similar way to our other properties. If we want to enable sorting on these inner array values, we will need to convert **all** the queries into aggregation queries which might be more that were bargaining for.
> 
> Instead, If we want to sort bids by recency and price, I would recommend we add an entirely new endpoint to retrieve bids specifically and enable bid sorting on that. Otherwise, it just wouldnt work in a usable way or make a lot of sense. I would suggest: GET DomainsByActiveBids and GET ActiveBidsByDomainId

resolved in an offline convo. We'll split sorting into its own story

**Comment by RyanCross** [comment]
> One open question:
> 
> Is it acceptable to expose the bid SignedMessage? Is that something that would be useful on the front end for the consumers? @RyanCross @JamesEarle @deep-quality-dev

AFAIK there's no harm in exposing it. Whether or not it's used is probably a frontend question (can check the current UX to see if it's being utilized on either app.wilderworld.com or zero.live)

**Review by RyanCross — APPROVED** [review]

**Pull request merged**
